name: Data Update Workflow

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 1 1,3,6,8,11 *"

jobs:
    update_data:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y jq curl

            - name: Get current year
              id: year
              run: echo "YEAR=$(date +'%Y')" >> $GITHUB_OUTPUT

            - name: Process missing directories
              id: process
              run: |
                  CHANGES_MADE=false
                  YEAR=${{ steps.year.outputs.YEAR }}
                  MAX_RETRIES=3

                  for i in 0 1; do
                    if [ ! -f "$YEAR/$i/data.json" ]; then
                      echo "Processing $YEAR/$i"
                      mkdir -p "$YEAR/$i"

                      success=false
                      for attempt in $(seq 1 $MAX_RETRIES); do
                        echo "Attempt $attempt of $MAX_RETRIES..."

                        response=$(curl -k -s -S --retry 3 --max-time 30 "https://catalog.sp.omu.ac.jp/api/search.json?year=$YEAR&semesters=$i" 2>&1)
                        exit_code=$?

                        if [ $exit_code -eq 0 ]; then
                          echo "$response" | jq '.data' > "$YEAR/$i/data.json"
                          if [ -s "$YEAR/$i/data.json" ]; then
                            echo "Successfully saved data to $YEAR/$i/data.json"
                            success=true
                            CHANGES_MADE=true
                            break
                          else
                            echo "Warning: Empty data file was created"
                          fi
                        else
                          echo "Curl failed with exit code $exit_code"
                          echo "Response/Error: $response"
                        fi

                        echo "Retrying in 5 seconds..."
                        sleep 5
                      done

                      if [ "$success" = false ]; then
                        echo "Failed to fetch data for $YEAR/$i after $MAX_RETRIES attempts"
                      fi
                    fi
                  done

                  echo "CHANGES_MADE=$CHANGES_MADE" >> $GITHUB_OUTPUT

            - name: Git commit and push
              if: ${{ steps.process.outputs.CHANGES_MADE == 'true' }}
              run: |
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Actions"
                  git add "${{ steps.year.outputs.YEAR }}"
                  git commit -m "Update data for ${{ steps.year.outputs.YEAR }}"
                  git push origin
